name: Called Workflow

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string
      param2:
        required: true
        type: string


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Show the event name
        run: |
          echo "This workflow was triggered by the event: ${{ github.event_name }}"
          
          param1_lower=$(echo "${{ inputs.param1 }}" | tr '[:upper:]' '[:lower:]')
          param2_lower=$(echo "${{ inputs.param2 }}" | tr '[:upper:]' '[:lower:]')

          echo "Converted param1 to lowercase: $param1_lower"
          echo "Converted param2 to lowercase: $param2_lower"
