name: Chaining Jobs

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        default: "World"
      city:
        description: "City of the person to greet"
        required: true
        default: "Mumbai"
        type: choice
        options: ["Mumbai", "Delhi", "Bangalore", "Chennai"]
      favorite_color:
        description: "Favorite color of the person to greet"
        required: true
        type: choice
        default: "Blue"
        options: ["Red", "Green", "Blue", "Yellow"]

jobs:
    job-1:
        name: Job 1
        runs-on: ubuntu-latest
        steps:
            - name: Output for Job 1
              run: |
                echo "Hello from Job 1. Run Job 3 equals ${{ github.event.inputs.run-job-3 }}"

    job-2:
        name: Job 2
        runs-on: ubuntu-latest
        needs: job-1
        steps:
            - name: Output for job 2
              run: echo "Hello from Job 2"
            - name: Make job 2 fail
              run: exit 1
    
    job-3:
        name: Job 3
        if: github.event.inputs.run-job-3 == 'true'
        runs-on: ubuntu-latest
        needs: job-1
        steps:
            - name: Output for job 3
              run: echo "Hello from Job 3"
    
    job-4:
        name: Job 4
        #if: always() #always want to run this job
        runs-on: ubuntu-latest
        needs: [job-2, job-3]
        steps:
            - name: Output for job 4
              run: echo "Hello from Job 4"
