name: Variables and Context

on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Name of the person to greet'
                required: true
                default: 'World'

env:
    VAR1: myworkflowvar1       
    VAR2: myworkflowvar2
    VAR3: myworkflowvar3

jobs:
    job1:
        runs-on: ubuntu-latest
        
        steps:
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
